const TAG_MAP: Record<string, string> = {
  // Core genres
  "角色扮演": "RPG",
  "模拟": "Simulation",
  "动作": "Action",
  "冒险": "Adventure",
  "策略": "Strategy",
  "休闲": "Casual",
  "射击": "Shooter",
  "格斗": "Fighting",
  "竞技": "Competitive",
  "竞速": "Racing",
  "体育": "Sports",
  "解谜": "Puzzle",
  "益智": "Brain Teaser",
  "音乐": "Music",
  "音游": "Rhythm Game",
  "节奏": "Rhythm",
  "教育": "Educational",

  // Sub-genres
  "卡牌": "Card",
  "放置": "Idle",
  "回合制": "Turn-based",
  "塔防": "Tower Defense",
  "沙盒": "Sandbox",
  "生存": "Survival",
  "建造": "Building",
  "经营": "Management",
  "模拟经营": "Business Sim",
  "养成": "Raising Sim",
  "收集": "Collection",
  "种田": "Farming",
  "开放世界": "Open World",
  "跑酷": "Parkour",
  "消除": "Match",
  "自走棋": "Auto Chess",
  "弹幕射击": "Bullet Hell",
  "弹幕": "Bullet Hell",
  "飞行射击": "Shoot 'em Up",
  "搜打撤": "Loot & Scoot",
  "割草": "Hack & Slash",
  "刷宝": "Loot Grinder",
  "闯关": "Level-based",
  "平台跳跃": "Platformer",
  "合成": "Merge",
  "下落式": "Drop Puzzle",
  "钓鱼": "Fishing",
  "狩猎": "Hunting",
  "烹饪": "Cooking",
  "装扮": "Dress Up",
  "换装": "Dress Up",
  "换装游戏": "Dress Up",
  "捏脸": "Character Creator",
  "家装": "Home Decor",
  "装修": "Renovation",
  "收纳": "Organization",
  "涂色": "Coloring",
  "绘画": "Drawing",
  "拼图": "Jigsaw",
  "找茬": "Spot Difference",
  "寻物解谜": "Hidden Object",
  "推理": "Deduction",
  "侦探": "Detective",
  "密室": "Escape Room",
  "逃生": "Escape",
  "潜行": "Stealth",
  "暗杀": "Assassination",
  "战棋": "Tactical RPG",
  "战争": "War",
  "军事": "Military",
  "海战": "Naval Combat",
  "航海": "Sailing",
  "太空": "Space",
  "飞行": "Flying",
  "模拟飞行": "Flight Sim",
  "赛车": "Racing",
  "坦克": "Tank",
  "摩托车": "Motorcycle",

  // Art style & presentation
  "二次元": "Anime",
  "像素": "Pixel Art",
  "3D": "3D",
  "2D": "2D",
  "卡通": "Cartoon",
  "手绘": "Hand-drawn",
  "Q版": "Chibi",
  "唯美": "Aesthetic",
  "高画质": "High Quality Graphics",
  "可爱": "Cute",
  "水墨": "Ink Wash",
  "艺术": "Art",

  // Themes & settings
  "国风": "Chinese Style",
  "武侠": "Wuxia",
  "仙侠": "Xianxia",
  "修仙": "Cultivation",
  "古风": "Ancient Chinese",
  "古装": "Period Costume",
  "三国": "Three Kingdoms",
  "西游": "Journey to the West",
  "封神": "Investiture of Gods",
  "山海经": "Classic of Mountains",
  "国战": "Nation War",
  "中世纪": "Medieval",
  "克苏鲁": "Cthulhu",
  "赛博朋克": "Cyberpunk",
  "科幻": "Sci-Fi",
  "魔幻": "Fantasy",
  "暗黑": "Dark",
  "末日": "Post-Apocalyptic",
  "末世": "Apocalypse",
  "废土": "Wasteland",
  "丧尸": "Zombie",
  "僵尸": "Zombie",
  "恐怖": "Horror",
  "悬疑": "Mystery",
  "恐龙": "Dinosaur",
  "宠物": "Pet",
  "猫": "Cat",
  "海洋": "Ocean",
  "都市": "Urban",
  "都市怪谈": "Urban Legend",
  "新怪谈": "New Weird",
  "怪谈": "Strange Tales",
  "校园": "School",
  "童年": "Childhood",
  "童话": "Fairy Tale",
  "神话": "Mythology",
  "历史": "History",
  "宫廷": "Royal Court",
  "穿越": "Time Travel",
  "异世界": "Isekai",
  "反乌托邦": "Dystopia",
  "机甲": "Mecha",
  "机器人": "Robot",
  "吸血鬼": "Vampire",
  "魔物娘": "Monster Girl",
  "盗墓": "Tomb Raiding",
  "美食": "Food",
  "昆虫": "Insect",
  "动物": "Animal",

  // Multiplayer & social
  "多人联机": "Multiplayer Online",
  "单机": "Offline",
  "社交": "Social",
  "PVP": "PVP",
  "PVE": "PVE",
  "合作": "Co-op",
  "共斗": "Co-op Combat",
  "多人合作": "Multiplayer Co-op",
  "团队合作": "Team Co-op",
  "多人竞技": "Multiplayer Arena",
  "派对游戏": "Party Game",
  "大乱斗": "Brawl",
  "吃鸡": "Battle Royale",
  "狼人杀": "Werewolf",
  "大型多人在线": "MMO",
  "线上对战": "Online PvP",
  "实时对战": "Real-time PvP",
  "1v1": "1v1",
  "3V3": "3v3",
  "5V5": "5v5",
  "自由交易": "Free Trade",

  // Game acronyms
  "MMORPG": "MMORPG",
  "ARPG": "ARPG",
  "RPG": "RPG",
  "FPS": "FPS",
  "TPS": "TPS",
  "MOBA": "MOBA",
  "SLG": "SLG",
  "AVG": "Visual Novel",
  "RTS": "RTS",
  "SRPG": "SRPG",
  "CCG": "CCG",
  "DBG": "Deckbuilder",
  "dbg": "Deckbuilder",
  "TCG": "TCG",
  "SOC": "SOC",
  "MUD": "MUD",
  "GalGame": "Gal Game",
  "APRG": "ARPG",
  "io": "io",

  // Roguelike variants
  "Roguelike": "Roguelike",
  "轻度Roguelike": "Roguelite",
  "轻度roguelike": "Roguelite",
  "轻度rogue": "Roguelite",
  "rogue-lite": "Roguelite",
  "Rougelike": "Roguelike",
  "Rogueike": "Roguelike",
  "Roguglike": "Roguelike",
  "roguglike": "Roguelike",
  "RougeLike": "Roguelike",
  "轻度Rougelike": "Roguelite",
  "轻度Rogulike": "Roguelite",
  "割草roguelike": "Hack & Slash Roguelite",
  "割草 Roguelike": "Hack & Slash Roguelite",

  // Platform / distribution
  "Steam移植": "Steam Port",
  "Steam 移植": "Steam Port",
  "steam 移植": "Steam Port",
  "steam移植版": "Steam Port",
  "移植": "Port",
  "独立游戏": "Indie",
  "买断制": "Premium",
  "付费下载": "Paid Download",
  "内购解锁": "IAP Unlock",
  "无内购": "No IAP",
  "抢先体验": "Early Access",
  "支持手柄": "Controller Support",
  "多端账号互通": "Cross-platform",
  "应用": "App",
  "媒体": "Media",
  "网络工具": "Network Tool",

  // Player experience descriptors
  "剧情": "Story-driven",
  "叙事": "Narrative",
  "文字": "Text-based",
  "热血": "Action-packed",
  "治愈": "Healing",
  "搞笑": "Comedy",
  "致郁": "Depressing",
  "催泪": "Tearjerker",
  "佛系": "Zen",
  "解压": "Relaxing",
  "烧脑": "Brain-burning",
  "硬核": "Hardcore",
  "高难度": "High Difficulty",
  "高自由度": "High Freedom",
  "魔性": "Addictive",
  "真实模拟": "Realistic Sim",
  "怀旧": "Nostalgic",
  "复古": "Retro",
  "复古怀旧": "Retro Nostalgic",
  "少年": "Shonen",

  // Specific orientation & visual
  "竖屏": "Portrait Mode",
  "横版": "Side-scrolling",
  "2D横版": "2D Side-scrolling",
  "俯视角": "Top-down",
  "上帝视角": "God View",
  "体感": "Motion Control",
  "互动电影": "Interactive Movie",
  "真人互动": "FMV",
  "真人影像": "Live Action",
  "动画改编": "Anime Adaptation",
  "小说改编": "Novel Adaptation",

  // Female-oriented
  "女性向": "Otome",
  "乙女": "Otome",
  "恋爱": "Romance",
  "美少女": "Bishoujo",

  // Specific IPs / brands
  "崩坏": "Honkai",
  "死神": "Bleach",
  "宝可梦": "Pokemon",
  "奥特曼": "Ultraman",
  "王者荣耀": "Honor of Kings",
  "初音未来": "Hatsune Miku",
  "仙剑": "Chinese Paladin",
  "饥荒": "Don't Starve",
  "诡秘之主": "Lord of Mysteries",
  "最终幻想": "Final Fantasy",
  "火柴人": "Stickman",
  "迪士尼": "Disney",
  "漫威": "Marvel",
  "怪物猎人": "Monster Hunter",
  "真人快打": "Mortal Kombat",
  "三国杀": "Legends of Three Kingdoms",
  "洛克人": "Mega Man",
  "游戏王": "Yu-Gi-Oh",
  "NBA": "NBA",
  "2K": "2K",
  "CS": "CS",

  // Other
  "积木": "Block Building",
  "街机": "Arcade",
  "桌游": "Board Game",
  "桌面和棋类": "Board & Chess",
  "抓宠": "Pet Catching",
  "捉宠": "Pet Catching",
  "萌宠": "Cute Pet",
  "拟人": "Anthropomorphic",
  "舰娘": "Ship Girl",
  "变身": "Transformation",
  "手速": "Reflex",
  "点击": "Clicker",
  "弹射": "Pinball",
  "大富翁": "Monopoly",
  "扑克": "Poker",
  "麻将": "Mahjong",
  "打砖块": "Breakout",
  "背包管理": "Inventory Management",
  "自动化": "Automation",
  "战术": "Tactical",
  "战斗": "Combat",
  "即时制": "Real-time",
  "即时战略": "RTS",
  "即时战术": "Real-time Tactical",
  "家园": "Homestead",
  "魔法": "Magic",
  "创作": "Creation",
  "生活": "Life",
  "偶像": "Idol",
  "舞蹈": "Dance",
  "篮球": "Basketball",
  "排球": "Volleyball",
  "足球": "Football",
  "逆塔防": "Reverse Tower Defense",
  "非对称竞技": "Asymmetric PvP",
  "类银河恶魔城": "Metroidvania",
  "银河恶魔城": "Metroidvania",
  "类魂": "Souls-like",
  "魂系": "Souls-like",
  "暗黑Like": "Diablo-like",
  "需家长陪同": "Parental Guidance",
  "聚光灯GameJam": "Spotlight Game Jam",
  "UP主推荐": "Creator's Pick",
  "AI": "AI",
  "AR": "AR",
  "Vocaloid": "Vocaloid",
  "meta": "Meta",
  "Furry": "Furry",
  "DIY": "DIY",
  "SEEC": "SEEC",
  "拟真": "Realistic",
  "国潮": "Chinese Trend",
  "国漫": "Chinese Animation",
  "日系": "Japanese Style",
  "日漫": "Japanese Anime",
  "动漫": "Anime",
  "横版动作": "Side-scrolling Action",
  "开罗": "Kairosoft",
  "雷亚": "Rayark",
  "潮玩": "Designer Toy",
  "西方魔幻": "Western Fantasy",
  "民俗": "Folklore",
  "文物": "Cultural Heritage",
  "古典": "Classical",
  "岩彩": "Mineral Pigment",
  "卡宏鼓": "Cajon",
  "山水": "Landscape",
  "妖怪": "Yokai",
  "心理学": "Psychology",
  "反应": "Reaction",
  "脑洞": "Creative",
  "次世代美术": "Next-gen Art",
  "放置挂机": "AFK Idle",
  "模拟驾驶": "Driving Sim",
  "驾驶": "Driving",
  "家庭": "Family",
  "餐厅": "Restaurant",
  "空战": "Aerial Combat",
  "火车": "Train",
  "飞机": "Airplane",
  "探案": "Investigation",
  "星战": "Star Wars",
  "刺激": "Thrilling",
  "探索": "Exploration",
  "物理": "Physics",
};

export function translateTag(tag: string): string {
  return TAG_MAP[tag] ?? tag;
}

export function translateTags(tags: string[]): string[] {
  return tags.map(translateTag);
}
